[supabase]
SUPABASE_URL = "https://hmrftqougofiigklkave.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcmZ0cW91Z29maWlna2xrYXZlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDcyMzc0MCwiZXhwIjoyMDYwMjk5NzQwfQ.v1nKYSogiel64zj4CHgfN0YzCtniFDXwjJxtUl4hEEo"